task_12
DrawGun/thinknetica_golang pull request #12
Opened 2020-12-10 15:07 UTC by DrawGun

Что-то я увлекся задачей. 
Не стал реализовывать логику смены подачи и логику результата (11:10). Надеюсь, в такой реализации примете.

2020-12-10 15:09 UTC, DrawGun commented on task_12/pingpong/pingpong.go
> +	player2 player
нравится нравится, что фигурирует конкретное число игроков, но, думаю, что чисто для пинпонга это число заведомо известно

2020-12-10 15:11 UTC, DrawGun commented on task_12/pingpong/pingpong.go
> +		g.server = &g.player1
не додумался, как правильнее делать подобную логику переключения активности игрока, подскажите, какой вариант правильный?

2020-12-14 03:41 UTC, DmitriyVTitov requested changes
Задача должна закрепить знания о каналах как средстве синхронизации работы потоков. Это не продемонстрировано.

2020-12-14 03:41 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +	player2 player
странно, что в игре три игрока (p1, p2, server)

2020-12-14 03:41 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +		g.server = &g.player1
правильный вариант - использовать канал.
если поток одного игрока пишет в канал, то прочитать может только поток другого игрока.
канал по своему устройству является средством синхронизации, поэтому достаточно просто отправить сообщение в канал и запустить два потока-игрока.
один из них первым прочитает сообщение о начале игры, а дальше они будут чередоваться.

2020-12-14 03:41 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +	fmt.Printf("Подает игрок -> %v: %s\n", g.server.name, hit)
подача только при первом ударе

2020-12-14 03:41 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +}
вот это совершенно бессмысленно.
операции записи и чтения в канале строго последовательны.

2020-12-17 04:22 UTC, DmitriyVTitov requested changes
Не обрабатывается факт выигрыша подачи. Счёт увеличивается по ходу игры без смены подачи.

Розыгрыш не может начинаться с "Pong".

```
Игрок Player_2 -> Ping
Игрок Player_1 -> Pong
Игрок Player_2 -> Ping
Игрок Player_1 -> Pong
Игрок Player_2 -> Ping
	Успешная подача!!!
Игрок Player_1 -> Pong
Игрок Player_2 -> Ping
Игрок Player_1 -> Pong
	Успешная подача!!!
```

2020-12-17 04:22 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +}
можно заменить на однострочник типа `if rand(5) == 0 {...}`

2020-12-17 04:22 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +	}
увеличение счёта происходит без остановки розыгрыша.
т.е. просто так, игроки продолжают играть.

2020-12-19 15:43 UTC, DrawGun commented on task_12/pingpong/pingpong.go
> +}
поменял, но мне автоматически исправило на 
```
        if rand.Intn(100) < p {
		return true
	}
```

2020-12-19 15:46 UTC, DrawGun commented on task_12/pingpong/pingpong.go
> +	}
Поправил

2020-12-19 15:50 UTC, DmitriyVTitov commented on task_12/pingpong/pingpong.go
> +}
> поменял, но мне автоматически исправило на
> 
> ```
>         if rand.Intn(100) < p {
> 		return true
> 	}
> ```

в смысле переноса на новую строку? это `gofmt`, это нормально
я бы вообще всю эту функцию удалил, она не добавляет ни логики ни компактности

2020-12-19 19:06 UTC, DrawGun commented on task_12/pingpong/pingpong.go
> +}
согласен, раньше предполагалось, что для кода нужно больше одного рандомного выбора, поэтому и селал подобный метод

2020-12-22 15:22 UTC, DmitriyVTitov approved these changes
Решено, всё хорошо.

2020-12-22 15:41 UTC, merged