task_13
DrawGun/thinknetica_golang pull request #13
Opened 2020-12-13 13:18 UTC by DrawGun

2020-12-13 13:24 UTC, DrawGun commented on task_13/pkg/storage/memstore/memstore.go
> +	err = ioutil.WriteFile(webDocumentsFile, encodedDocs, 0666)
так как мы работаем с файлом, я не нашел ничего лучшего, как брать существующие данные добавлять новые документы и полностью перезаписывать сам файл, заучит как глупость, думаю, с появлением полноценной DB эта проблема сама собой отпадет

2020-12-13 13:25 UTC, DrawGun commented on task_13/pkg/storage/memstore/memstore.go
> +		doc.ID = db.id
меняю идентификатор, чтобы синхронизировать его с ID стораджа

2020-12-17 04:00 UTC, DmitriyVTitov requested changes
Всегда важно понимать как завершатся все создаваемые потоки.

2020-12-17 04:00 UTC, DmitriyVTitov commented on task_13/cmd/gosearch/main.go
> +
в коде нигде не вызывается wg.Wait(), следовательно эта конструкция используется неверно.
также нигде не закрывается канал rawDocs (связано с предыдущем пунктом).
в результате поток чтения результатов утёк и никогда не завершится.

2020-12-19 20:14 UTC, DrawGun commented on task_13/cmd/gosearch/main.go
> +
поправил

2020-12-22 15:32 UTC, DmitriyVTitov requested changes
Проблема не исправлена. У вас открывается каналов больше, чем закрывается (в частности rawDocs не закрывается нигде). Из-за этого "утекает" поток обработки результатов - GC его никогда не уберёт.
Не буду подсказывать, оставляю вам задачу определить правильное место для закрытия канала.

2020-12-23 11:52 UTC, DmitriyVTitov approved these changes
ОК

2020-12-23 11:53 UTC, merged