task_3
DrawGun/thinknetica_golang pull request #3
Opened 2020-10-26 12:25 UTC by DrawGun

Что-то я намудрил ). Хотел сделать, чтобы main.go оперировал только pkg/engine, но когда все начал собирать вместе, то понял, что налицо ошибка проектирования, так как я не пойму кто кого должен вызывать и кому подчиняться.

2020-10-26 12:27 UTC, DrawGun commented on task_3/cmd/go.mod
> +replace pkg/crawler => ../../task_3/pkg/crawler
не понял, зачем это тут нужно, так как в самом main я не использую pkg/crawler, но go упорно не хотел запускаться, только после этого replace, заработал, странно

2020-10-26 12:28 UTC, DrawGun commented on task_3/cmd/main.go
> +	results, err := eng.Scan(eng.Crw)
Это моя попытка запустить сканирование в engine в рамках задачи. Сам вижу, что неособо, но как сделать правильно я так и не понял. Подскажите, плиз.

2020-10-28 16:09 UTC, DmitriyVTitov requested changes
Всё очень сложно и запутанно. Пакет `engine` вообще можно убрать и вынести код в `main` пока что.
Попробуйте начать с чистого листа. Пример поискового робота + интерфейс + пакет-заглушка:
https://github.com/hardcode-dev/go-core/tree/master/gosearch/crawler

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/cmd/go.mod
> +replace pkg/crawler => ../../task_3/pkg/crawler
потому что `engine` вызывает `crawler`
поэтому `main` должен знать где все пакеты лежат

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/crawler/crawler.go
> +}
вот тип

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/crawler/crawler.go
> +}
вот метод, который должен реализовывать контракт интерфейса
ищем интерфейс )

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/engine/engine.go
> +}
вот и интерфейс

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/engine/engine.go
> +}
а вот и функция, которая его вызывает

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/engine/engine.go
> +func (e *Engine) Scan(s Scanner) (map[string]string, error) {
вот только из сигнатуры не понятно что она сканирует. она принимает только интерфейс и всё.
а где этот интерфейс возьмёт ссылки на сайты для сканирования? их-то, по идее, тоже надо в эту функцию передать, чтобы она прошла по ним циклом и для каждой ссылки вызвала `s.Scan(url, depth)`

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/engine/engine.go
> +func New(url string, depth int) *Engine {
крайне странное решение: зачем поисковому движку (обработчику поисковых запросов) в конструкторе передавать какую-то ссылку и какую-то глубину?
он должен получать объект поискового робота, с помощью которого он бы отсканировал сайты

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/engine/engine.go
> +}
этот не "интерфейс для работы с crawler", потому что у бота такого метода (без аргументов) нет

2020-10-28 16:09 UTC, DmitriyVTitov commented on task_3/pkg/crawler/crawler.go
> +}
а, метод таки есть, и он берёт ссылку и глубину из состояния объекта.
а если я захочу два сайта отсканировать?

2020-10-28 16:26 UTC, DrawGun commented
@DmitriyVTitov только внес правки в свою реализацию а через минуту получил ревью. 
Немного понял что такое интерфейсы только после пояснения в 4 уроке. Правильно я понимаю, что это своеобразная попытка в ООП?
Попробую переделать с учетом замечаний

2020-10-28 16:37 UTC, DmitriyVTitov commented
> Правильно я понимаю, что это своеобразная попытка в ООП?

В такой формулировке, понятия не имею, правильно ли вы понимаете :)

2020-10-30 17:28 UTC, DmitriyVTitov approved these changes
Получается, что заглушку написал я, а не вы :)
ОК, но вот функция Results из одной строки не имеет особого смысла.

2020-10-30 17:28 UTC, DmitriyVTitov commented on task_3/cmd/main.go
> +}
у всех вот такая вот функция. один в один.
и она одинаково бессмысленная.

2020-10-30 17:28 UTC, DmitriyVTitov commented on task_3/cmd/main.go
> +func search(res []crawler.Document, phrase string) []string {
функция обрабатывает массив документов, а возвращает странную строку.
почему не возвращает документы?
так невозможно тестировать.

2020-10-30 17:28 UTC, DmitriyVTitov commented on task_3/cmd/main_test.go
> +}
учитывая саму тестируемую функцию, тест также не имеет смысла

2020-10-30 19:29 UTC, merged