task_4
DrawGun/thinknetica_golang pull request #4
Opened 2020-10-30 00:00 UTC by DrawGun

2020-10-30 00:01 UTC, DrawGun commented on task_4/cmd/main.go
> +	webData, err := spid.Results(spid)
выглядит как-то странно, но работает, не уверен, что так правильно делать

2020-10-30 00:03 UTC, DrawGun commented on task_4/pkg/index/index.go
> +			return doc.ID >= id
не совсем понял почему прямое сравнение `doc.ID == id` всегда возвращает максимальную длину массива

2020-10-30 00:05 UTC, DrawGun commented on task_4/pkg/index/index.go
> +		i.ParseAndFillIndex(document.ID, document.URL, "/", "?#:")
думаю, что сохранение в индексе частей урла излишне, на автомате добавил и их

2020-11-01 11:52 UTC, DmitriyVTitov requested changes
Не могу принять код с такой бессмысленной функцией с извращённой конструкцией. Тот факт, что что-то работает, не означает что так можно или, тем более, нужно писать.

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/cmd/go.sum
> +golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
в .gitignore!

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/cmd/main.go
> +	webData, err := spid.Results(spid)
очень странно! наверняка это ошибка.

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/cmd/main.go
> +	webData, err := spid.Results(spid)
плюс имя функции вообще ничего не говорит

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/cmd/main.go
> +	ind.Process()
"Процесс" что? Что обработать?

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +}
в чём заключается "попытка"? может не получиться?
для чего сюда передаётся интерфейс? то есть вообще странная конструкция, смысл которой я понять не могу. даже идею не понимаю (пускай и ошибочную).

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +	depth   int
почему-то результаты заданий как под копирку! все запихивают эту ссылку в структуру, в итоге сканер получается одноразовый, на один сайт. а почему?
зачем вообще убирать аргументы из функции сканирования?

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +}
вот какой смысл этой функции? в ней одна строка, для чего эта функция нужна? что она привносит?

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/pkg/index/index.go
> +			return doc.ID >= id
`doc.ID == id` не может вернуть длину массива, потому что операторы сравнения возвращают булево значение, а длина - число.
Длина массива поиском возвращается в случае, если элемент не найден. См. документацию.

2020-11-01 11:52 UTC, DmitriyVTitov commented on task_4/pkg/index/index.go
> +// Process заполняет индекс исходя из данных в storage
это невозможно понять из названия

2020-11-01 12:09 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +}
попытка заключается в том, что я не до конца понял реализацию интерфейсов, в примере interface2 была подобная реализация(printInfo), именно поэтому такая функция

2020-11-01 12:16 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +	depth   int
А что, собственно, не так? В данный конкретный момент я хочу просканировать определенный сайт, вот и добавляю дополнительные настройки для этого. если захочу просканировать другой - создам новый экземпляр `spider.New` разве это работает не так?

2020-11-01 12:17 UTC, DrawGun commented on task_4/cmd/go.sum
> +golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
реализовано в предидущем задании

2020-11-01 12:23 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +}
вы можете показать правильный пример использования в одном из следующих занятий?

2020-11-01 12:57 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +}
Так я много раз показывал. У вас пакет `spider` должен сам отвечать за реализацию интерфейса `Scanner`. И вот один из его методов требует этот интерфейс. Нелогично же! Этот метод сам должен реализовать контракт интерфейса, а он интерфейс требует.
В пакете `spider` вообще не нужны переменные типа `Scanner`. Они нужны там, где вызывается метод сканирования. То есть в коде, который **использует** пакет `spider`. В вашем случае это исполняемый пакет.

2020-11-01 13:00 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +}
в прошлом задании вам пример функции, которая вызывает только один метод `spid.Scan` не понравился вот я и подумал, что это неправильно и решил попробовать реализовать что-то другое

2020-11-01 13:01 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +	depth   int
Можно и так. Я у вас такой код в реальной задаче бы не принял.

2020-11-01 13:02 UTC, DmitriyVTitov commented on task_4/cmd/go.sum
> +golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
если "реализовано", то что файл делает здесь? вот же он!
ну не смешно.

2020-11-01 13:04 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +	depth   int
Вполне возможно, что вы правы, пожалуйста, объясните чуть подробнее почему

2020-11-01 13:06 UTC, DrawGun commented on task_4/cmd/go.sum
> +golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
объясню, я сделал 3 задание с этим фиксом и не дожидаясь апрува приступил к выполнению четвертого
мердж с актуальнам мастером добавит соответствующую правку в .gitignore, файл удалю со следующим коммитом

2020-11-01 13:12 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +}
так и здесь вырожденная функция из одной строки, чем лучше-то стало?

2020-11-01 13:16 UTC, DmitriyVTitov commented on task_4/pkg/crawler/spider/spider.go
> +	depth   int
Ну вот сканируете вы 1_000_000 сайтов. создаёте 1_000_000 объектов, это давление на сборщик мусора. Этот аргумент неочевиден.
Вот ещё более сложный: вы создаёте сканер не там, где используете и передаёте как зависимость. Создав новый сканер, вам нужно будет как-то обновить его в других объектах.
А вот очевидный: сканер, вполне возможно, захочет иметь собственное постоянное состояние. В вашей реализации это невозможно.

2020-11-01 13:21 UTC, DrawGun commented on task_4/pkg/crawler/spider/spider.go
> +}
справедливо
но ничего лучшего я не придумал, как реализовать ее как запуск функции элемента класса `spider`, сначала подумал, что так не надо будет получать переменную `Spider` в нее, но оказалось, что показалось.
В общем еще один тупик, поэтому я озвучил просьбу выше. К тому же Вы не опровергли и не подтвердили правильность реализации функции `Results` в предидущем задании, что ставит меня опять в ситуацию неопределенности.

2020-11-05 20:11 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-05 20:11 UTC, DmitriyVTitov commented on task_4/cmd/main.go
> +	webData, err := Results(spid, url, depth)
почему функция сканирования называется "Результаты"?

2020-11-05 20:11 UTC, DmitriyVTitov commented on task_4/cmd/main.go
> +}
вы так и не удалили эту бессмысленную функцию с плохим именем?
к тому же она зачем-то экспортируемая

2020-11-06 09:13 UTC, merged