task_9
DrawGun/thinknetica_golang pull request #9
Opened 2020-12-03 17:26 UTC by DrawGun

Внес правки по замечаниям к task_8 и написал просто бенчмарк для `StoreDocs`

2020-12-05 01:28 UTC, DmitriyVTitov requested changes
1. Каждый модульный тест должен быть в своём пакете.
2. Имена тестов очень важны, и для них есть схема. Если вы схему не помните - используйте генератор тестов в IDE и не переименовывайте тест без крайней необходимости (у вас её не наблюдается, но можете привести аргументы - я далеко не всегда прав).

2020-12-05 01:28 UTC, DmitriyVTitov commented on task_9/pkg/storage/memstore/memstore_test.go
> +}
1 функция -1 тест (по крайней мере в имени второго быть не должно)

2020-12-05 01:28 UTC, DmitriyVTitov commented on task_9/pkg/storage/memstore/memstore_test.go
> +}
тест (как и бенчмарк) должен быть в своём пакете.
интеграционных бенчмарков тут не требуется.

2020-12-08 00:00 UTC, DmitriyVTitov requested changes
Для дерева тестов нет.
Нужно сравнить массив и дерево в плане производительности вставки и поиска и где-нибудь написать результат.

2020-12-08 00:00 UTC, DmitriyVTitov commented on task_9/pkg/storage/memstore/memstore_test.go
> +func Benchmark_StoreDocs(b *testing.B) {
подчёркивание лишнее (или так IDE назвала?)

2020-12-08 00:00 UTC, DmitriyVTitov commented on task_9/pkg/btree/btree_test.go
> +
где тесты для дерева-то?

2020-12-08 14:44 UTC, DrawGun commented on task_9/pkg/storage/memstore/memstore_test.go
> +func Benchmark_StoreDocs(b *testing.B) {
нет я сам, поправлю

2020-12-08 22:29 UTC, DrawGun commented on task_9/pkg/btree/btree_test.go
> +
написал

2020-12-08 22:35 UTC, DrawGun commented
Для массива:
```
pkg: thinknetica_golang/task_9/pkg/search/array
Benchmark_Insert-8       4788048               241 ns/op             313 B/op          0 allocs/op
Benchmark_Search-8      47725396                23.3 ns/op             0 B/op          0 allocs/op
PASS
ok      thinknetica_golang/task_9/pkg/search/array      3.105s
```

Для btree:
```
pkg: thinknetica_golang/task_9/pkg/search/btree
Benchmark_Insert-8         37960            139006 ns/op              80 B/op          1 allocs/op
Benchmark_Search-8      51027973                21.0 ns/op             0 B/op          0 allocs/op
PASS
ok      thinknetica_golang/task_9/pkg/search/btree      7.565s
```

2020-12-11 04:45 UTC, DmitriyVTitov approved these changes
Какие результаты сравнения?

2020-12-11 04:45 UTC, DmitriyVTitov commented on task_9/pkg/search/array/array.go
> +package array
чё-то я не понял, это пакет только для тестов? а смысл?

2020-12-11 04:45 UTC, DmitriyVTitov commented on task_9/pkg/search/array/array_test.go
> +}
какой-то сизифов труд, по-моему

2020-12-11 04:45 UTC, DmitriyVTitov commented on task_9/pkg/search/array/array.go
> +package array
разобрался, пакет с массивом в качестве хранилища не было просто.
тогда странный каталог `/pkg/search/array`, лучше уж `/pkg/storage/array`. это всё же хранилище документов.

2020-12-11 04:47 UTC, DmitriyVTitov commented
> Для `array`:
> 
> ```
> pkg: thinknetica_golang/task_9/pkg/search/array
> Benchmark_Insert-8       4788048               241 ns/op             313 B/op          0 allocs/op
> Benchmark_Search-8      47725396                23.3 ns/op             0 B/op          0 allocs/op
> PASS
> ok      thinknetica_golang/task_9/pkg/search/array      3.105s
> ```
> 
> Для `btree`:
> 
> ```
> pkg: thinknetica_golang/task_9/pkg/search/btree
> Benchmark_Insert-8         37960            139006 ns/op              80 B/op          1 allocs/op
> Benchmark_Search-8      51027973                21.0 ns/op             0 B/op          0 allocs/op
> PASS
> ok      thinknetica_golang/task_9/pkg/search/btree      7.565s
> ```

странные результаты, у других получилась вставка быстрее в дерево, а поиск в массиве. причём и то и то различалось существенно.

2020-12-11 08:18 UTC, merged